# Generated by Django 2.1.7 on 2019-02-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='diskripsi_produk',
            field=models.TextField(),
        ),
    ]
